### ISSUE TITLE
Unable to set cookie

### ISSUE THREAD

**Issue by bobl61** [Rosenstein/PsychoStats-Drek282#102]
I've uploaded your fork and still having the same problem. The installer will not set the cookie:
![2023-04-20_194220](https://user-images.githubusercontent.com/107001969/233508958-d5828b04-7f13-47cb-89e4-ca81614dc9c7.png)

**Comment by Rosenstein** [comment]
This forks main branch is always up to date with Drek282/PsychoStats. Other branches are not, and rarely updated.
We already solved this in Drek's repo.
